apiVersion: apps/v1
kind: Deployment
metadata:
  name: licensing-example-java
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: licensing-example-java
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: licensing-example-java
  template:
    metadata:
      labels:
        app.kubernetes.io/name: licensing-example-java
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8080
          volumeMounts:
            {{- if .Values.subscriptionSecret.enabled }}
            - name: license-volume
              mountPath: "/var/subscription"
            {{- end }}
      volumes:
        {{- if .Values.subscriptionSecret.enabled }}
        - name: license-volume
          secret:
            secretName: license-subscription
        {{- end }}
      affinity:
        {{- toYaml .Values.affinity | nindent 8 }}
