apiVersion: v1
kind: Service
metadata:
  name: licensing-example-java
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  publishNotReadyAddresses: true
  selector:
    app.kubernetes.io/name: licensing-example-java
