apiVersion: v1
kind: Service
metadata:
  name: web
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  clusterIP: None
  internalTrafficPolicy: Cluster
  sessionAffinity: None
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
  publishNotReadyAddresses: true
  selector:
    app.kubernetes.io/name: licensing-example-java
