name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ] 
  merge_group:
    branches: [ "main" ]

permissions:
  contents: read  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 21 for x64
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'
        architecture: x64

    - name: Clean and compile the project
      run: mvn clean install
      
    - name: Run the Maven verify phase
      run: mvn --batch-mode --update-snapshots verify

  tag:
    if: github.event_name == 'push'
    needs: [build]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    concurrency:
      group: Tag-'${{ github.workflow }}'
    steps: 
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
