# yaml-language-server: $schema=https://api.omnistrate.cloud/2022-09-01-00/schema/service-spec-schema.json
# yaml-language-server: $schema=https://api.omnistrate.cloud/2022-09-01-00/schema/system-parameters-schema.json

name: licensing-example-java

features:
  licensing:
    licenseExpirationInDays: 7 # optional - defaults to 7 days
    productPlanUniqueIdentifier: 'PRODUCT-SAMPLE-JAVA-SKU-UNIQUE-VALUE'

services:
  - name: licensing-example-java
    endpointConfiguration:
      cluster:
        host: $sys.network.externalClusterEndpoint
        ports:
          - 443
        primary: true
        networkingType: PUBLIC
    helmChartConfiguration:
      chartName: licensing-example-java
      chartVersion: 0.1.3
      chartRepoName: licensing-example-java
      chartRepoURL: https://omnistrate-community.github.io/licensing-example-java
      chartValues:
        replicaCount: 1
        image:
          repository: ghcr.io/omnistrate-community/licensing-example-java
          pullPolicy: IfNotPresent
          tag: "0.1.5"
        ingress:
          enabled: true
          className: nginx
          host: $sys.network.externalClusterEndpoint
        subscriptionSecret:
          enabled: true
        affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
                - matchExpressions:
                  - key: omnistrate.com/managed-by
                    operator: In
                    values:
                    - omnistrate
                  - key: topology.kubernetes.io/region
                    operator: In
                    values:
                    - $sys.deploymentCell.region
                  - key: node.kubernetes.io/instance-type
                    operator: In
                    values:
                    - $sys.compute.node.instanceType
                  - key: omnistrate.com/resource
                    operator: In
                    values:
                    - $sys.deployment.resourceID
          podAntiAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                - key: omnistrate.com/schedule-mode
                  operator: In
                  values:
                  - exclusive
              namespaceSelector: {}
              topologyKey: kubernetes.io/hostname