replicaCount: 1

image:
  repository: ghcr.io/omnistrate-community/licensing-example-java
  pullPolicy: IfNotPresent
  tag: "latest"

service:
  type: ClusterIP
  port: 80

resources: {}
nodeSelector: {}
tolerations: []
affinity: {}

subscription-secret:
  enabled: true
  name: "license-subscription"
  mountPath: "/var/"
