# Copyright Omnistrate, Inc. All Rights Reserved.
# SPDX-License-Identifier: APACHE-2.0

apiVersion: v2
name: licensing-example-java
description: Helm chart for licensing-example-java
type: application
keywords:
- omnistrate
- licensing
- example
maintainers:
- name: Omnistrate, Inc.. All Rights Reserved.
  url: https://omnistrate.com
sources:
- https://github.com/omnistrate-community/licensing-example-java

version: 0.1.6
appVersion: "1.0"
