replicaCount: 1

image:
  repository: ghcr.io/omnistrate-community/licensing-example-java
  pullPolicy: IfNotPresent
  tag: "latest"

ingress:
  enabled: true
  className: nginx
  host: www.service.cloud
  tls: true
  tlsSecret: google-public-ca-tls

subscriptionSecret:
  enabled: true

instanceId: "unique-deployment-id"

useTerraform: false

endpoints:
  dbEndpoint1: ""       # {{ $terraformChild.out.db_endpoints_1 }}
  dbEndpoint2: ""       # {{ $terraformChild.out.db_endpoints_2.endpoint }}
  redisEndpoint: ""     # {{ $terraformChild2.out.redis_endpoint }}
  pubsubId: ""          # {{ $terraformChild2.out.pubsub_id }}

