replicaCount: 1

image:
  repository: ghcr.io/omnistrate-community/licensing-example-java
  pullPolicy: IfNotPresent
  tag: "latest"

ingress:
  enabled: true
  className: nginx
  host: instance-fpi05qn33.hc-pelsk80ph.us-east-2.aws.f2e0a955bb84.cloud

subscriptionSecret:
  enabled: true
