replicaCount: 1

image:
  repository: ghcr.io/omnistrate-community/licensing-example-java
  pullPolicy: IfNotPresent
  tag: "latest"

ingress:
  enabled: true
  className: nginx
  host: www.service.cloud
  tls: true
  tlsSecret: google-public-ca-tls

subscriptionSecret:
  enabled: true

instanceId: "unique-deployment-id"
