name: Package Chart

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ] 
  
env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io

jobs:
  release:
    # depending on default permission settings for your org (contents being read-only or read-write for workloads), you will have to add permissions
    # see: https://docs.github.com/en/actions/security-guides/automatic-token-authentication#modifying-the-permissions-for-the-github_token
    permissions:
      contents: write
      packages: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
          
      - name: Set up Helm
        uses: azure/setup-helm@v4

      - name: Log into registry ${{ env.REGISTRY }}
        if: github.event_name == 'release'
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Package and Push Helm Chart
        run: |
          cd charts/helm
          # Get chart version from Chart.yaml
          CHART_VERSION=$(grep '^version:' Chart.yaml | awk '{print $2}')
          CHART_NAME=$(grep '^name:' Chart.yaml | awk '{print $2}')
          
          # Package the chart
          helm package .
          
          # Push to GitHub Container Registry
          helm push "${CHART_NAME}-${CHART_VERSION}.tgz" oci://ghcr.io/${{ github.repository_owner }}