name: Release

on:
  release:
    types: [ "published" ]
  workflow_dispatch:
    inputs:
      create-instance:
        description: 'Whether to create an instance after updating the plan'
        type: boolean
        required: false
        default: false

jobs:
  # First job: Build and publish Docker images using existing package workflow
  package-docker:
    name: Package Docker Images
    uses: ./.github/workflows/package.yml
    permissions:
      contents: read
      packages: write
      id-token: write
    secrets: inherit

  # Second job: Package and publish Helm charts using existing package-charts workflow
  package-charts:
    name: Package Helm Charts
    needs: package-docker
    uses: ./.github/workflows/package-charts.yml
    permissions:
      contents: write
      packages: write
    secrets: inherit

  # Third job: Release plan to Omnistrate using existing
  release-to-omnistrate:
    name: Release to Omnistrate
    needs: package-charts
    uses: ./.github/workflows/release-to-omnistrate.yaml
    permissions:
      contents: read
    secrets: inherit


  # Fourth job: Validate deployment in Omnistrate using existing
  validate-deployment:
    name: Validate Deployment in Omnistrate
    needs: release-to-omnistrate
    if: ${{ github.event.inputs.create-instance == 'true' || github.event_name == 'release' }}
    uses: ./.github/workflows/validate-deployment.yaml
    permissions:
      contents: read
    secrets: inherit



  
